### PR TITLE
Update to aws v3

### PR DESCRIPTION
**Pull request by moritzraho**
## Description

This PR updates the S3 SDK to v3 from v2. 

The usage of v2 shows an ugly warning when deploying assets:
```
aio app deploy
⠋ Updating log forwarding configuration(node:10089) NOTE: The AWS SDK for JavaScript (v2) will be put into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
✔ Built 2 action(s) for 'dx/excshell/1'
✔ Building web assets for 'dx/excshell/1'
✔ Deployed 4 action(s) for 'dx/excshell/1'
✔ Deploying web assets for 'dx/excshell/1'
```

Another reason to update is that v3 takes a modular approach and will help us reduce CLI dependencies size by a good amount, see: https://github.com/adobe/aio-cli/issues/349

## Tests

This has been tested with:
- unit tests
- linking aio cli and running `aio app deploy --skip-actions`
- linking aio cli and running `aio app undeploy --skip-actions`

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by moritzraho** [comment]
Please let me know if we could tests other things.

Also note that there is a little perf regression for files > 100MB and a hard limit on > 5GB files as we do not use multipart uploads anymore, but unless we use RemoteStorage in other places, this shouldn't be an issue for web assets.

**Comment by MichaelGoberling** [comment]
LGTM! Do we know how much smaller v3 is vs. including all of v2?

**Review by MichaelGoberling — APPROVED** [review]

**Comment by moritzraho** [comment]
thanks for the review @MichaelGoberling. Good point.

I ran `npx cost-of-modules` in the master branch:
```
┌─────────────────────────────┬────────────┬────────┐
│ name                        │ children   │ size   │
├─────────────────────────────┼────────────┼────────┤
│ aws-sdk                     │ 0          │ 77.08M │
├─────────────────────────────┼────────────┼────────┤
│ core-js                     │ 0          │ 1.07M  │
├─────────────────────────────┼────────────┼────────┤
│ joi                         │ 0          │ 0.50M  │
├─────────────────────────────┼────────────┼────────┤
│ @adobe/aio-lib-core-tvm     │ 0          │ 0.16M  │
├─────────────────────────────┼────────────┼────────┤
│ fs-extra                    │ 0          │ 0.06M  │
├─────────────────────────────┼────────────┼────────┤
│ lodash.clonedeep            │ 0          │ 0.05M  │
├─────────────────────────────┼────────────┼────────┤
│ parcel                      │ 0          │ 0.04M  │
├─────────────────────────────┼────────────┼────────┤
│ @adobe/aio-lib-core-config  │ 0          │ 0.03M  │
├─────────────────────────────┼────────────┼────────┤
│ regenerator-runtime         │ 0          │ 0.03M  │
├─────────────────────────────┼────────────┼────────┤
│ @adobe/aio-lib-core-logging │ 0          │ 0.02M  │
├─────────────────────────────┼────────────┼────────┤
│ mime-types                  │ 0          │ 0.02M  │
├─────────────────────────────┼────────────┼────────┤
│ klaw                        │ 0          │ 0.01M  │
├─────────────────────────────┼────────────┼────────┤
│ 12 modules                  │ 0 children │ 79.05M │
└─────────────────────────────┴────────────┴────────┘
```

And now in the new PR branch:

```
┌─────────────────────────────┬────────────┬───────┐
│ name                        │ children   │ size  │
├─────────────────────────────┼────────────┼───────┤
│ @aws-sdk/client-s3          │ 0          │ 3.53M │
├─────────────────────────────┼────────────┼───────┤
│ core-js                     │ 0          │ 1.07M │
├─────────────────────────────┼────────────┼───────┤
│ joi                         │ 0          │ 0.50M │
├─────────────────────────────┼────────────┼───────┤
│ @adobe/aio-lib-core-tvm     │ 0          │ 0.16M │
├─────────────────────────────┼────────────┼───────┤
│ fs-extra                    │ 0          │ 0.06M │
├─────────────────────────────┼────────────┼───────┤
│ lodash.clonedeep            │ 0          │ 0.05M │
├─────────────────────────────┼────────────┼───────┤
│ parcel                      │ 0          │ 0.04M │
├─────────────────────────────┼────────────┼───────┤
│ @adobe/aio-lib-core-config  │ 0          │ 0.03M │
├─────────────────────────────┼────────────┼───────┤
│ regenerator-runtime         │ 0          │ 0.03M │
├─────────────────────────────┼────────────┼───────┤
│ @adobe/aio-lib-core-logging │ 0          │ 0.02M │
├─────────────────────────────┼────────────┼───────┤
│ mime-types                  │ 0          │ 0.02M │
├─────────────────────────────┼────────────┼───────┤
│ klaw                        │ 0          │ 0.01M │
├─────────────────────────────┼────────────┼───────┤
│ 12 modules                  │ 0 children │ 5.51M │
└─────────────────────────────┴────────────┴───────┘
```

**Comment by shazron** [comment]
Codecov in this repo hasn't been migrated from the bash script, so it won't run. Suggest  just override the checks and merge instead of waiting for codecov (if locally it is 100% coverage that is)

**Comment by shazron** [comment]
https://github.com/adobe/aio-lib-web/pull/176

**Comment by moritzraho** [comment]
Will do some more testing to be 100% sure and then merge, we can release next week

**Comment by moritzraho** [comment]
Did some more testing with BYO credentials and truncated directories
good to go

**Pull request merged**
