### PR TITLE
feat: Response Header support

### PR DESCRIPTION
**Pull request by sandeep-paliwal**
DO NOT MERGE
Support to specify response headers, by adding them to S3 metadata. 
Rules to apply response headers are read from config and are applied based on order they were specified.

Note: This change is dependent on - https://github.com/adobe/aio-cli-lib-app-config . Util changes in  app config lib are released and referenced inside web lib these changes should not be merged.
## How Has This Been Tested?
Manual e2e and automated unit tests

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by purplecabbage — COMMENTED** [review]
This looks good, but I think we need to be extremely careful with files/patterns.
Instead of your parsing file paths in canAddHeader I think we should use: path.extname(), path.basename() etc.

It might make sense to use glob for expansion as well.

**Review by moritzraho — COMMENTED** [review]
Two things:
1. I agree with Jesse, + using path joins might not work as expected on windows machines?
2. I would advocate having all the validation as part of https://github.com/adobe/aio-cli-lib-app-config. For the following reasons:
- fail fast and inform users that the config is wrong on the first command, not only on deploy
- keep all the configuration validation in one place => easier to maintain. Especially knowing that we will support a json schema for the app config at some point meaning that part of the config will be handled by the schema itself. 

One drawback is that if the web library is used independently we don't get the validation. But that could be mitigated in the future by exposing a `validation` function from the config lib.

**Comment by sandeep-paliwal** [comment]
> Two things:
> 
> 1. I agree with Jesse, + using path joins might not work as expected on windows machines?
> 2. I would advocate having all the validation as part of https://github.com/adobe/aio-cli-lib-app-config. For the following reasons:
> 
> * fail fast and inform users that the config is wrong on the first command, not only on deploy
> * keep all the configuration validation in one place => easier to maintain. Especially knowing that we will support a json schema for the app config at some point meaning that part of the config will be handled by the schema itself.
> 
> One drawback is that if the web library is used independently we don't get the validation. But that could be mitigated in the future by exposing a `validation` function from the config lib.
> 
> EDIT: I understand 2. may require significant added effort, if it's easier I am also ok with keeping a note [here](https://github.com/adobe/aio-cli-lib-app-config/issues/11) and revisiting this once we introduce the config schema

Thanks @moritzraho . Yes I agree with part suggested by Jesse to use inbuilt path API for validation and few more extensive tests to cover windows.
On the suggestion to move this to app-config, there are a few reasons the application of rules sits here

- These are not config validations but application of rules present in config used at time file is being deployed. Similar to the way we use cache config and apply it to file when its deployed.
- Config need not know about these business logic it should just load a valid config. But the web storage lib needs to apply valid headers based on the config rules and so this is a better place to apply the config rules. WDYT?

**Comment by moritzraho** [comment]
Ok then sounds good to keep the rules here then. Maybe in the future we can offload some of the validation in the schema itself.

**Review by purplecabbage — APPROVED** [review]

**Pull request merged**
